### ISSUE TITLE
Switching profiles causes NVDA Remote to be disconnected unexpectedly.

### ISSUE THREAD

**Issue by cary-rowen** [nvda-es/NVDARemote#31] opened 2023-12-15 01:33 UTC
1. NVDA+Ctrl+P:Create a new application profile.
2. Connect remotely in common profile.
3. Switch to the application with the new profile.

After performing the above steps, the remote was accidentally disconnected.

**Comment by amirmahdifard** [comment] 2023-12-15 21:38
@cary-rowen i guess this happens because the tele nvda catigory in the nvda settings dialog only supports normal configuration profile and not others, exactly like the general catigory. i'm willing to fix this but i don't know how. Tele nvda catigory should support profiles. Even speech history catigory supports profiles. i'll try to look at speech history's code to see if i can support it in nvda as whel.

**Comment by jmdaweb** [comment] 2023-12-16 08:56
Hi,
I need more information. Do you connect as controller or controlled? Can you reproduce this issue with all other add-ons disabled? Is any traceback printed to the log? Do you receive any alert, such as disconnection sound and message?
We experienced a similar issue caused by add-ons such as Wake Speaker. When a profile was activated on the remote machine, the controller stopped hearing the remote voice.
Regards.

**Comment by amirmahdifard** [comment] 2023-12-17 00:45
@jmdaweb 1: do you plan to add supporting profiles to tele nvda catigory? 2: i can also gather information

**Comment by amirmahdifard** [comment] 2023-12-17 08:28
@jmdaweb even before this issue, i was looking in to this, that tele nvda doesn't supports any other profiles and only normal configuration, but speech history and addon updator for example does.
what i mean, look at these steps.
1: go to an application, like notepad.
2: create a trigger profile for notepad.
3: go to nvda settings dialog.
the first is general catigory which also doesn't support profiles, so, press your down arrow key once.
before your nvda says speech 2 of 19 for example, it says editing notepad first, and then it says speech 2 of 19.
 now, arrow down until reaching tele nvda, before your nvda says tele nvda 18 of 19, it says editing normal configuration, and then it says tele nvda 18 of 19, exactly like general catigory.
 this shouldn't be the case of tele nvda, for example when i want to have difrent settings in difrent profiles in my tele nvda addon. i tryed to solve this but i'm not sure at all what to do. i tryed some things in the dialogs.py but i got crashed the addon.
 so, can you please fix this or a little help me so i can do it? thanks a lot if you read this answer me.

**Comment by jmdaweb** [comment] 2023-12-17 08:34
Hi,
TeleNVDA won't support multiple profiles for now. It doesn't make sense. Those add-ons don't support profiles, but authors forgot switching to normal profile when opening their settings categories. That is not a real profile change, it's a way to notify you that these settings aren't profile-aware.
Regarding the main purpose of this issue, all feedback is welcome.
Regards.

**Comment by amirmahdifard** [comment] 2023-12-17 12:11
@jmdaweb can i know the reason why it shouldn't support multipul profiles? for example, i can uncheck the Process speech commands when controlling another computer  check box in my notepad profile, but enable it in the normal configuration.

**Comment by cary-rowen** [comment] 2023-12-19 11:43
> I need more information. Do you connect as controller or controlled? Can you reproduce this issue with all other add-ons disabled? Is any traceback printed to the log? Do you receive any alert, such as disconnection sound and message?
Hi, I am controlling another machine.

No other add-ons were disabled for testing.

I'm using Wake Speaker

**Comment by jmdaweb** [comment] 2023-12-19 11:46
CC: @davidacm

**Comment by cary-rowen** [comment] 2023-12-21 11:42
Yes, after further testing on my part, this is indeed an issue caused by wakeSpeaker.
cc @davidacm can you take a look at this?

**Comment by davidacm** [comment] 2023-12-31 10:35
Hi @cary-rowen  and @jmdaweb, the issue is present in the first versions of wake speaker. I think the problem was fixed in the latest version, can you try it?
this is the link to the latest version:
[wake Speaker 23.5.2](https://github.com/davidacm/WakeSpeaker/releases/download/23.5.2/WakeSpeaker-23.5.2.nvda-addon)

**Comment by cary-rowen** [comment] 2023-12-31 23:10
Hi @davidacm 
Thanks for the new version. Can you publish this version to the add-on store?
If you would like me to assist you with this process that is no problem.
Anyway, please let me know.

**Comment by davidacm** [comment] 2024-01-01 00:02
That version was launched in may 2023, but I forgot to publish it in the add-on store. I will update the compatibility version for the NVDA 2024, and then i will launch a new version.

I need to create an automatized process to publish new versions of my add-ons, I usually forget to do it. Hehe.

I'm closing this issue since is related with other add-ons. Some add-ons still can affect speak functions and cause the same issue, but is a thing that need to be changed in the core of NVDA to deal it in a better way.

Thanks for the report and the collaboration! :)

**Closed as completed by davidacm** 2024-01-01 00:02 UTC
